Allow source and target to be specified by env vars

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,23 +2,26 @@
 
 # Usage: bin/detect BUILD_DIR
 
-if [[ -f $1/web/package.json && -d $1/api/public ]]; then
-  echo "Compile-frontend"
-  exit 0
+if [[ -z ${FRONTEND_BUILDPACK_SOURCE_DIR} ]]; then
+  exec 1>&2
+  echo "FATAL: Please set env var: FRONTEND_BUILDPACK_SOURCE_DIR"
+  exit 1
 fi
 
-exec 1>&2
-
-if [[ ! -f $1/web/package.json ]]; then
-  echo "FATAL: Missing expected file: web/package.json"
+if [[ -z ${FRONTEND_BUILDPACK_TARGET_DIR} ]]; then
+  exec 1>&2
+  echo "FATAL: Please set env var: FRONTEND_BUILDPACK_TARGET_DIR"
+  exit 1
 fi
 
-if [[ ! -f $1/api/public ]]; then
-  echo "FATAL: Missing expected target dir: api/public/"
+source_requirement=$1/${FRONTEND_BUILDPACK_SOURCE_DIR}/package.json
+
+if [[ ! -f ${source_requirement} ]]; then
+  exec 1>&2
+  echo "FATAL: Missing expected file: ${source_requirement}"
+  echo "Ensure that this file is present in the top level dir, which currently contains these files/dirs:"
+  ls -1p "$1"
+  exit 1
 fi
 
-echo "Ensure that these are present in the top level dir, which currently contains these files/dirs:"
-
-ls -1p "$1"
-
-exit 1
+echo "Compile-frontend"
